services:
  backend:
    build:
      context: ../metier-back
      dockerfile: ../CICD-run/backend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/app/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/demo
    networks:
      - app-network

  frontend:
    build:
      context: ../metier-front
      dockerfile: ../CICD-run/frontend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  h2-data: